openapi: 3.0.0
info:
  title: SmartJob CRUD API
  description: API para gestionar usuarios y teléfonos
  version: 1.0.0
servers:
  - url: http://localhost:8080

paths:
  /api/users/register:
    post:
      summary: Registrar un nuevo usuario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Usuario'
      responses:
        '201':
          description: Usuario creado exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Usuario'
        '400':
          description: Error en la solicitud

components:
  schemas:
    Phone:
      type: object
      properties:
        id:
          type: integer
          format: int64
        number:
          type: string
        cityCode:
          type: string
        countryCode:
          type: string

    Usuario:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        email:
          type: string
        password:
          type: string
        phones:
          type: array
          items:
            $ref: '#/components/schemas/Phone'
        created:
          type: string
          format: date-time
        modified:
          type: string
          format: date-time
        lastLogin:
          type: string
          format: date-time
        token:
          type: string
        isActive:
          type: boolean
