spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
custom:
  passwordRegex: "^(?=.*[a-zA-Z])(?=.*\\d).+$"
  emailRegex: "^[a-zA-Z]+@[a-zA-Z]+\\.[a-zA-Z]{2,}$"